//> using lib "tech.neander::langoustine-lsp::0.0.17"
//> using lib "tech.neander::jsonrpclib-fs2::0.0.4"
//> using lib "co.fs2::fs2-io::3.3.0"
//> using scala "3.2.0"
//> using lib "org.typelevel::cats-parse::0.3.8"
//> using lib "io.chrisdavenport::crossplatformioapp::0.1.0"
