//> using lib "tech.neander::langoustine-lsp::0.0.7"
//> using lib "tech.neander::jsonrpclib-fs2::0.0.3"
//> using lib "co.fs2::fs2-io::3.2.11"
//> using scala "3.1.3"
//> using lib "org.typelevel::cats-parse::0.3.8"
