name: CI
on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' 
          java-version: '17'
          cache: 'sbt'

      - uses: VirtusLab/scala-cli-setup@main

      - name: CI
        run: make all

